version: '2.1'
orbs:
  grype: anchore/grype@0.2.0
workflows:
  integration-test_deploy:
    jobs:
      - grype/list-image-vulns:
          image-name: kr1ps/mairejava
          
      - grype/list-image-vulns:
          image-name: kr1ps/mairejava
          fail-on-severity: high #options=[negligible low medium high crditical]