orbs:
  anchore: anchore/anchore-engine@1
version: 2.1
workflows:
  scan_image:
    jobs:
      - anchore/image_scan:
          image_name: 'docker.io/anchore/anchore-engine:latest'
          timeout: '300'
